disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - trailing_newline
  - line_length
  #- vertical_whitespace
  - identifier_name
  - force_try
  - force_cast
  - xctfail_message
  - empty_enum_arguments
  - function_parameter_count

opt_in_rules:
  - operator_usage_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods


